#!/usr/bin/env python3
"""
AI Paper Annotator — HTML Generator
Usage:  python generate.py paper.json [--out output.html]

Expected folder layout (next to paper.json):
  figures/figure_1.png      ← user places screenshots here
  tables/table_1.json       ← generated by TABLE_SKILL
  style.css                 ← must be in the same folder as the output HTML
"""

import json
import sys
import argparse
import html as html_lib
import os
from pathlib import Path

# ── Constants ──────────────────────────────────────────────────────────────────

LEGEND = [
    ("concept",  "核心概念 / 模型架構"),
    ("problem",  "現有方法問題 / 研究缺口"),
    ("solution", "本文解法 / 技術貢獻"),
    ("method",   "方法細節 / 實作說明"),
    ("result",   "實驗設定 / 數據比較"),
]

ROLE_COLOURS = {
    "問題定義":     "#ef4444",
    "研究動機":     "#f97316",
    "文獻回顧":     "#a855f7",
    "方法提出":     "#22c55e",
    "模型元件描述": "#22c55e",
    "實作細節":     "#eab308",
    "實驗設計":     "#3b82f6",
    "結果分析":     "#3b82f6",
    "消融實驗":     "#06b6d4",
    "侷限討論":     "#6b7280",
    "結論":         "#8b5cf6",
}

HIGHLIGHT_LEGEND_STYLES = {
    "concept":  ("#ede9fe", "#5b21b6"),
    "problem":  ("#fee2e2", "#991b1b"),
    "solution": ("#dcfce7", "#166534"),
    "method":   ("#fef9c3", "#854d0e"),
    "result":   ("#dbeafe", "#1e40af"),
}

EVO_HOVER_JS = """
(function () {
  // Shared floating panel (evo-path click panel + fishbone hover tooltip)
  var tip = document.createElement('div');
  tip.className = 'evo-tooltip';
  tip.style.display = 'none';
  document.body.appendChild(tip);

  function escH(s) {
    return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
  }

  function nodeCard(label, note) {
    var h = '<div class="evo-tip-card"><span class="evo-tip-label">' + escH(label) + '</span>';
    if (note) h += '<span class="evo-tip-note">' + escH(note) + '</span>';
    h += '</div>';
    return h;
  }

  function positionTip(anchorRect) {
    var tipW = tip.offsetWidth  || 280;
    var tipH = tip.offsetHeight || 140;
    var x = anchorRect.right + 12;
    var y = anchorRect.top + (anchorRect.height - tipH) / 2;
    if (x + tipW > window.innerWidth  - 8) x = anchorRect.left - tipW - 12;
    if (y < 8) y = 8;
    if (y + tipH > window.innerHeight - 8) y = window.innerHeight - tipH - 8;
    tip.style.left = x + 'px';
    tip.style.top  = y + 'px';
  }

  // ── Evolutionary Path (click to open / click outside to close) ───────────────
  document.querySelectorAll('.evo-svg').forEach(function (svg) {
    var nodeGroups = Array.from(svg.querySelectorAll('.evo-node-group'));
    var edgeGroups = Array.from(svg.querySelectorAll('.evo-edge-group'));
    var activeNid  = null;

    var nodeInfo = {};
    nodeGroups.forEach(function (ng) {
      nodeInfo[ng.dataset.nid] = { label: ng.dataset.label || '', note: ng.dataset.note || '' };
    });

    var adj = {};
    edgeGroups.forEach(function (eg) {
      var from = eg.dataset.from, to = eg.dataset.to, lbl = eg.dataset.elabel || '';
      if (!adj[from]) adj[from] = [];
      if (!adj[to])   adj[to]   = [];
      adj[from].push({ nid: to,   elabel: lbl, dir: 'out' });
      adj[to].push(  { nid: from, elabel: lbl, dir: 'in'  });
    });

    function clearActive() {
      activeNid = null;
      nodeGroups.forEach(function (ng) {
        var rect = ng.querySelector('.evo-node-rect');
        if (rect) rect.style.opacity = '';
        ng.querySelectorAll('text').forEach(function (t) { t.style.opacity = ''; });
      });
      edgeGroups.forEach(function (eg) {
        var line = eg.querySelector('line');
        if (line) line.style.opacity = '';
      });
      tip.style.display = 'none';
    }

    function activateNode(nid, rectEl) {
      activeNid = nid;
      var visible = new Set([nid]);
      (adj[nid] || []).forEach(function (c) { visible.add(c.nid); });

      nodeGroups.forEach(function (ng) {
        var show = visible.has(ng.dataset.nid);
        var rect = ng.querySelector('.evo-node-rect');
        if (rect) rect.style.opacity = show ? '1' : '0.18';
        ng.querySelectorAll('text').forEach(function (t) {
          // Non-neighbor labels dimmed but still readable; other text hidden
          if (t.classList.contains('evo-label')) {
            t.style.opacity = show ? '1' : '0.3';
          } else {
            t.style.opacity = show ? '1' : '0';
          }
        });
      });
      edgeGroups.forEach(function (eg) {
        var show = visible.has(eg.dataset.from) && visible.has(eg.dataset.to);
        var line = eg.querySelector('line');
        if (line) line.style.opacity = show ? '1' : '0.1';
      });

      var info = nodeInfo[nid] || { label: nid, note: '' };
      var html = nodeCard(info.label, info.note);
      (adj[nid] || []).forEach(function (conn) {
                      
        var arrow = conn.dir === 'out' ? '&#8594;' : '&#8592;';
        html += '<div class="evo-tip-edge">' + arrow + (conn.elabel ? ' ' + escH(conn.elabel) : '') + '</div>';

        // html += '<div class="evo-tip-edge">&#8593;</div>';
        var nInfo = nodeInfo[conn.nid] || { label: conn.nid, note: '' };
        html += nodeCard(nInfo.label, nInfo.note);
      });
      tip.innerHTML = html;
      tip.style.display = 'block';
      positionTip(rectEl.getBoundingClientRect());
    }

    nodeGroups.forEach(function (ng) {
      var rect = ng.querySelector('.evo-node-rect');
      if (!rect) return;
      rect.addEventListener('click', function (ev) {
        ev.stopPropagation();
        if (activeNid === ng.dataset.nid) { clearActive(); }
        else { activateNode(ng.dataset.nid, rect); }
      });
    });

    // Click outside SVG closes the panel
    document.addEventListener('click', function () {
      if (activeNid !== null) clearActive();
    });
    svg.addEventListener('click', function (ev) { ev.stopPropagation(); });
  });

  // ── Fishbone: effect ellipse (click) ─────────────────────────────────────────
  var activeFbEl = null;
  document.querySelectorAll('.fb-effect-group').forEach(function (eg) {
    eg.addEventListener('click', function (ev) {
      ev.stopPropagation();
      if (activeFbEl === eg) { activeFbEl = null; tip.style.display = 'none'; return; }
      activeFbEl = eg;
      var full = eg.dataset.fulltext || '';
      tip.innerHTML = '<div class="evo-tip-card">'
        + '<span class="evo-tip-label">研究問題</span>'
        + (full ? '<span class="evo-tip-note">' + escH(full) + '</span>' : '')
        + '</div>';
      tip.style.display = 'block';
      positionTip(eg.getBoundingClientRect());
    });
  });

  // ── Fishbone: categories (click) ─────────────────────────────────────────────
  document.querySelectorAll('.fb-cat-group').forEach(function (cg) {
    var catRect = cg.querySelector('.fb-cat-rect');
    if (!catRect) return;
    cg.addEventListener('click', function (ev) {
      ev.stopPropagation();
      if (activeFbEl === cg) { activeFbEl = null; tip.style.display = 'none'; return; }
      activeFbEl = cg;
      var cat   = cg.dataset.category || '';
      var items = [];
      try { items = JSON.parse(cg.dataset.items || '[]'); } catch(err) {}
      var html = nodeCard(cat, '');
      items.forEach(function (item) {
        html += '<div class="evo-tip-edge">&#8595;</div>';
        html += '<div class="evo-tip-card"><span class="evo-tip-note">' + escH(item) + '</span></div>';
      });
      tip.innerHTML = html;
      tip.style.display = 'block';
      positionTip(catRect.getBoundingClientRect());
    });
  });

  // ── Fishbone SVG: click on empty area closes pinned tooltip ──────────────────
  document.querySelectorAll('.fishbone-svg').forEach(function (fbSvg) {
    fbSvg.addEventListener('click', function (ev) {
      activeFbEl = null; tip.style.display = 'none';
      ev.stopPropagation();
    });
  });

  // ── Global: click outside fishbone SVG closes pinned tooltip ─────────────────
  document.addEventListener('click', function () {
    if (activeFbEl !== null) { activeFbEl = null; tip.style.display = 'none'; }
  });
})();
"""

SCROLL_JS = """
(function () {
  const pairs = Array.from(document.querySelectorAll('.pair[data-pair-idx]'));

  function parseRefs(pair) {
    const raw = pair.dataset.tblRefs || '';
    if (!raw) return {};
    const map = {};
    raw.split(';').forEach(part => {
      const [tid, rowsStr] = part.split(':');
      if (!tid) return;
      map[tid] = (rowsStr || '').split(',').map(Number).filter(n => !isNaN(n));
    });
    return map;
  }

  const pairRefs = pairs.map(parseRefs);

  function getTableRows(tid) {
    const tbl = document.getElementById(tid);
    if (!tbl) return [];
    return Array.from(tbl.querySelectorAll('tbody tr'));
  }

  function setRowStates(tid, activeRows) {
    getTableRows(tid).forEach((tr, i) => {
      tr.classList.toggle('row-active', activeRows.includes(i));
    });
  }

  function clearActiveRowsExcept(keepTid) {
    document.querySelectorAll('.data-table tbody tr.row-active').forEach(tr => {
      const tbl = tr.closest('.table-wrap');
      if (!tbl || tbl.id !== keepTid) tr.classList.remove('row-active');
    });
  }

  function clearAll() {
    document.querySelectorAll('.pair.is-active').forEach(p => p.classList.remove('is-active'));
    document.querySelectorAll('.data-table tbody tr.row-active').forEach(tr => {
      tr.classList.remove('row-active');
    });
  }

  function applyActive(idx) {
    if (idx < 0 || idx >= pairs.length) { clearAll(); return; }
    document.querySelectorAll('.pair.is-active').forEach(p => p.classList.remove('is-active'));
    const activePair = pairs[idx];
    activePair.classList.add('is-active');
    // Sync row-active highlight: clear old, apply new for this pair's refs
    const refs = pairRefs[idx] || {};
    const refTids = new Set(Object.keys(refs));
    document.querySelectorAll('.data-table tbody tr.row-active').forEach(tr => {
      const tbl = tr.closest('.table-wrap');
      if (!tbl || !refTids.has(tbl.id)) tr.classList.remove('row-active');
    });
    Object.entries(refs).forEach(([tid, rows]) => setRowStates(tid, rows));
  }

  // ── Active-pair detection (visible pair closest to viewport center) ────────
  const visible = new Set();
  const observer = new IntersectionObserver(entries => {
    entries.forEach(e => {
      const idx = parseInt(e.target.dataset.pairIdx, 10);
      if (e.isIntersecting) visible.add(idx); else visible.delete(idx);
    });
    pickActive();
  }, { threshold: 0.1 });

  pairs.forEach(p => observer.observe(p));

  function pickActive() {
    if (visible.size === 0) { clearAll(); return; }
    const viewMid = window.scrollY + window.innerHeight / 2;
    let best = -1, bestDist = Infinity;
    visible.forEach(idx => {
      const r = pairs[idx].getBoundingClientRect();
      const pairMid = window.scrollY + r.top + r.height / 2;
      const dist = Math.abs(pairMid - viewMid);
      if (dist < bestDist) { bestDist = dist; best = idx; }
    });
    applyActive(best);
  }

  window.addEventListener('scroll', pickActive, { passive: true });
})();
"""

# ── Helpers ────────────────────────────────────────────────────────────────────

def e(s) -> str:
    return html_lib.escape(str(s))

def render_en(content) -> str:
    if isinstance(content, str):
        return f"<p>{e(content)}</p>"
    parts = []
    for item in content:
        if isinstance(item, str):
            parts.append(e(item))
        elif isinstance(item, dict):
            t = item.get("type", "concept")
            parts.append(f'<mark class="hl hl-{t}">{e(item.get("text",""))}</mark>')
    return "<p>" + "".join(parts) + "</p>"

def render_annotation(ann: dict, role_colour: str) -> str:
    return f"""<div class="ann-card" style="border-left-color:{role_colour}">
      <span class="ann-role" style="background:{role_colour}">{e(ann.get("role",""))}</span>
      <div class="ann-section"><div class="ann-label">技術邏輯</div><div>{e(ann.get("logic",""))}</div></div>
      <div class="ann-section"><div class="ann-label">閱讀提示</div><div>{e(ann.get("note",""))}</div></div>
    </div>"""

# ── Figure ─────────────────────────────────────────────────────────────────────

def render_figure(block: dict, base_dir: Path) -> tuple[str, str]:
    fid    = block["id"]
    ftype  = block.get("type", "其他")
    aspect = block.get("aspect_ratio", "wide")
    ann    = block.get("annotation", {})

    fig_dir = base_dir / "figures"
    img_src = None
    for ext in [".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"]:
        if (fig_dir / (fid + ext)).exists():
            img_src = f"figures/{fid}{ext}"
            break

    img_html = (
        f'<img src="{img_src}" alt="{e(fid)}" class="fig-img fig-img--{aspect}">'
        if img_src else
        f'<div class="fig-placeholder">[ 請將 {e(fid)}.png / .jpg 放於 figures/ 資料夾 ]</div>'
    )

    left = f"""<div class="fig-wrap fig-wrap--{aspect}">
      <div class="fig-type-tag">{e(ftype)}</div>
      {img_html}
      <div class="fig-caption">
        <span class="fig-id">{e(fid.replace("_"," ").title())}</span>
        <span class="fig-cap-en">{e(block.get("caption_en",""))}</span>
        <div class="fig-cap-zh">{e(block.get("caption_zh",""))}</div>
      </div>
    </div>"""

    data_flow = ann.get("data_flow", "")
    right = f"""<div class="ann-card ann-card--figure">
      <span class="ann-role" style="background:#64748b">圖表批註</span>
      <div class="ann-section"><div class="ann-label">論點</div><div>{e(ann.get("argument",""))}</div></div>
      <div class="ann-section"><div class="ann-label">閱讀視覺重點</div><div>{e(ann.get("reading_tip",""))}</div></div>
      {"" if not data_flow else f'<div class="ann-section"><div class="ann-label">資料流向</div><div>{e(data_flow)}</div></div>'}
    </div>"""

    return left, right

# ── Table ──────────────────────────────────────────────────────────────────────

def load_table(blk: dict, base_dir: Path) -> dict | None:
    """Load table from tables/<table_id>.json. Returns None if file missing."""
    tid = blk.get("table_id", "")
    if not tid:
        return None
    tbl_path = base_dir / "tables" / f"{tid}.json"
    if tbl_path.exists():
        with open(tbl_path, encoding="utf-8") as f:
            return json.load(f)
    return None

def render_table_html(tbl: dict, referenced_rows: set) -> str:
    tid     = tbl["id"]
    headers = tbl.get("headers", [])
    rows    = tbl.get("rows", [])
    th_html = "".join(f"<th>{e(h)}</th>" for h in headers)
    tr_html = ""
    for i, row in enumerate(rows):
        cls = ' class="row-ref"' if i in referenced_rows else ""
        tds = "".join(f"<td>{e(c)}</td>" for c in row)
        tr_html += f"<tr{cls} data-row-idx='{i}'>{tds}</tr>"

    return f"""<div class="table-wrap" id="{e(tid)}">
      <div class="table-type-tag">數據表格</div>
      <table class="data-table">
        <caption>
          <strong>{e(tid.replace("_"," ").title())}</strong>&nbsp; {e(tbl.get("caption_en",""))}
          <br><span class="cap-zh">{e(tbl.get("caption_zh",""))}</span>
        </caption>
        <thead><tr>{th_html}</tr></thead>
        <tbody>{tr_html}</tbody>
      </table>
    </div>"""

def render_table_ann(tbl: dict) -> str:
    ann = tbl.get("annotation", {})
    return f"""<div class="ann-card ann-card--table">
      <span class="ann-role" style="background:#0f766e">表格批註</span>
      <div class="ann-section"><div class="ann-label">論點</div><div>{e(ann.get("argument",""))}</div></div>
      <div class="ann-section"><div class="ann-label">閱讀重點</div><div>{e(ann.get("reading_tip",""))}</div></div>
    </div>"""

def render_table_ref_snippet(blk: dict, tbl: dict | None) -> str:
    tid   = blk.get("table_id", "")
    cells = blk.get("cells", [])
    note  = blk.get("note", "")
    snippets = []
    if tbl:
        headers = tbl.get("headers", [])
        rows    = tbl.get("rows", [])
        for cell in cells:
            r, c = cell.get("row", 0), cell.get("col", 0)
            label = cell.get("label") or (headers[c] if c < len(headers) else f"col{c}")
            try:   val = rows[r][c]
            except IndexError: val = "N/A"
            snippets.append(
                f'<span class="cell-snippet"><span class="cell-label">{e(label)}</span> {e(val)}</span>'
            )
    inner = " ".join(snippets) if snippets else f'(參見 <a href="#{e(tid)}">{e(tid)}</a>)'
    return f'<div class="table-ref"><span class="table-ref-badge">↗ {e(tid.replace("_"," ").title())}</span> {inner}{"  —  " + e(note) if note else ""}</div>'

def refs_in_blocks(blocks: list) -> dict:
    out = {}
    for blk in blocks:
        if blk.get("block_type") == "table_ref":
            tid  = blk.get("table_id", "")
            rows = {c.get("row", 0) for c in blk.get("cells", [])}
            out.setdefault(tid, set()).update(rows)
    return out

# ── Diagrams ───────────────────────────────────────────────────────────────────

def _evo_border_pt(cx, cy, tx, ty, hw=54, hh=22):
    """Return the point on the node rect border (centered at cx,cy) toward (tx,ty)."""
    dx = tx - cx; dy = ty - cy
    if dx == 0 and dy == 0:
        return cx, cy
    adx = abs(dx); ady = abs(dy)
    if adx == 0:
        return cx, cy + (hh if dy > 0 else -hh)
    if ady == 0:
        return cx + (hw if dx > 0 else -hw), cy
    t = min(hw / adx, hh / ady)
    return cx + t * dx, cy + t * dy

def build_evolutionary_path(ep: dict) -> str:
    nodes = ep.get("nodes", [])
    edges = ep.get("edges", [])
    if not nodes:
        return ""

    # Group nodes by year so same-year nodes stack vertically with small x-jitter
    years = sorted(set(n["year"] for n in nodes))
    year_to_x = {y: 80 + i * 160 for i, y in enumerate(years)}

    nodes_by_year: dict = {}
    node_slot: dict = {}
    for n in nodes:
        nodes_by_year.setdefault(n["year"], []).append(n)
    for yr, lst in nodes_by_year.items():
        for slot, n in enumerate(lst):
            node_slot[n["id"]] = slot

    NODE_W, NODE_H = 108, 38
    ROW_GAP = 22
    X_JITTER = 14
    TOP_PAD = 50
    AXIS_PAD = 60

    node_map = {}
    for n in nodes:
        slot = node_slot[n["id"]]
        base_x = year_to_x[n["year"]]
        if slot == 0:
            dx = 0
        elif slot % 2 == 1:
            dx = X_JITTER * ((slot + 1) // 2)
        else:
            dx = -X_JITTER * (slot // 2)
        x = base_x + dx
        y = TOP_PAD + slot * (NODE_H + ROW_GAP) + NODE_H // 2
        node_map[n["id"]] = (x, y)

    max_per_year = max(len(lst) for lst in nodes_by_year.values())
    H = TOP_PAD + max_per_year * (NODE_H + ROW_GAP) + AXIS_PAD
    W = max(year_to_x.values()) + 140

    p = [
        f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" class="evo-svg" preserveAspectRatio="xMidYMid meet">',
        '<defs><marker id="arr" markerWidth="8" markerHeight="8" refX="8" refY="3" orient="auto">'
        '<path d="M0,0 L0,6 L8,3 z" fill="var(--evo-axis)"/></marker></defs>',
        f'<line x1="60" y1="{H-30}" x2="{W-20}" y2="{H-30}" stroke="var(--evo-axis)" stroke-width="1.5"/>',
    ]
    for yr, x in year_to_x.items():
        p.append(f'<text x="{x}" y="{H-10}" text-anchor="middle" class="evo-year" fill="var(--evo-year-fill)">{yr}</text>')
        p.append(f'<line x1="{x}" y1="{H-34}" x2="{x}" y2="{H-26}" stroke="var(--evo-axis)" stroke-width="1"/>')

    for edge in edges:
        fid, tid2 = edge.get("from"), edge.get("to")
        if fid in node_map and tid2 in node_map:
            x1,y1 = node_map[fid]; x2,y2 = node_map[tid2]
            sx,sy = _evo_border_pt(x1,y1,x2,y2,hw=NODE_W//2,hh=NODE_H//2)
            ex,ey = _evo_border_pt(x2,y2,x1,y1,hw=NODE_W//2,hh=NODE_H//2)
            elabel = e(edge.get("label", ""))
            p.append(f'<g class="evo-edge-group" data-from="{e(fid)}" data-to="{e(tid2)}" data-elabel="{elabel}">')
            p.append(f'<line x1="{sx:.1f}" y1="{sy:.1f}" x2="{ex:.1f}" y2="{ey:.1f}" stroke="var(--evo-axis)" stroke-width="1.5" marker-end="url(#arr)"/>')
            p.append('</g>')

    for n in nodes:
        x, y  = node_map[n["id"]]
        main  = n.get("is_this_paper", False)
        fill  = "var(--evo-main-bg)"     if main else "var(--evo-node-bg)"
        strk  = "var(--evo-main-border)" if main else "var(--evo-node-border)"
        tfill = "var(--evo-main-fg)"     if main else "var(--evo-node-text)"
        sw    = 2 if main else 1
        nlabel = e(n["label"])
        nnote  = e(n.get("note", ""))
        p.append(f'<g class="evo-node-group" data-nid="{e(n["id"])}" data-label="{nlabel}" data-note="{nnote}">')
        p.append(f'<rect x="{x-NODE_W//2}" y="{y-NODE_H//2}" width="{NODE_W}" height="{NODE_H}" rx="6" fill="{fill}" stroke="{strk}" stroke-width="{sw}" class="evo-node-rect"/>')
        p.append(f'<text x="{x}" y="{y+4}" text-anchor="middle" class="evo-label" fill="{tfill}">{nlabel}</text>')
        p.append('</g>')

    p.append("</svg>")
    return "\n".join(p)

def build_fishbone(fb: dict) -> str:
    effect = fb.get("effect", "")
    causes = fb.get("causes", [])
    if not causes: return ""

    # Dynamic sizing
    n = len(causes)
    SPINE_LEFT = 80
    BONE_STEP = 130          # horizontal distance between bone roots
    SPINE_TO_LABEL = 85      # vertical distance from spine to category label
    PAD_TOP = 30
    PAD_BOTTOM = 30
    ELLIPSE_RX = 50
    ELLIPSE_RY = 30
    HEAD_GAP = 20            # gap between last bone and ellipse left edge

    spine_length = max(n * BONE_STEP + 40, 500)
    head_x = SPINE_LEFT + spine_length
    W = head_x + 2 * ELLIPSE_RX + HEAD_GAP + 20  # ellipse fits with right padding
    H = SPINE_TO_LABEL * 2 + PAD_TOP + PAD_BOTTOM + 60
    spine_y = H // 2

    p = [
        f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" class="fishbone-svg" preserveAspectRatio="xMidYMid meet">',
        f'<rect x="0" y="0" width="{W}" height="{H}" fill="transparent" pointer-events="all"/>',
        f'<line x1="{SPINE_LEFT}" y1="{spine_y}" x2="{head_x}" y2="{spine_y}" stroke="var(--evo-node-border)" stroke-width="2.5"/>',
        f'<g class="fb-effect-group" data-fulltext="{e(effect)}" style="cursor:pointer">',
        f'  <ellipse cx="{head_x + HEAD_GAP + ELLIPSE_RX}" cy="{spine_y}" rx="{ELLIPSE_RX}" ry="{ELLIPSE_RY}" fill="var(--evo-main-bg)" stroke="var(--evo-main-border)" stroke-width="1"/>',
        f'  <text x="{head_x + HEAD_GAP + ELLIPSE_RX}" y="{spine_y+5}" text-anchor="middle" class="fb-effect" fill="var(--evo-main-fg)" style="pointer-events:none">研究問題</text>',
        f'</g>',
    ]
    colours = ["#7c3aed","#be123c","#0f766e","#b45309","#1d4ed8","#065f46"]
    for i, cause in enumerate(causes):
        x = SPINE_LEFT + 30 + i * BONE_STEP
        above = (i % 2 == 0)
        bone_y = spine_y - SPINE_TO_LABEL if above else spine_y + SPINE_TO_LABEL
        colour = colours[i % len(colours)]
        p.append(f'<line x1="{x}" y1="{spine_y}" x2="{x+35}" y2="{bone_y}" stroke="{colour}" stroke-width="2"/>')
        ty = bone_y + (-14 if above else 20)
        cat_text = cause.get("category", "")
        disp_cat = (cat_text[:11] + "…") if len(cat_text) > 11 else cat_text
        items_data = e(json.dumps(cause.get("items", []), ensure_ascii=False))
        rx_box = (x+35) - 32; ry_box = ty - 15; rw = 64; rh = 21
        p.append(f'<g class="fb-cat-group" data-category="{e(cat_text)}" data-items="{items_data}" style="cursor:pointer">')
        p.append(f'  <rect x="{rx_box}" y="{ry_box}" width="{rw}" height="{rh}" rx="4" fill="{colour}" fill-opacity="0.18" stroke="{colour}" stroke-width="1.5" class="fb-cat-rect"/>')
        p.append(f'  <text x="{x+35}" y="{ty}" text-anchor="middle" class="fb-category" fill="{colour}" style="pointer-events:none">{e(disp_cat)}</text>')
        p.append('</g>')
        # NOTE: item dots removed — items are shown only inside the click tooltip on the category
    p.append("</svg>")
    return "\n".join(p)

# ── Main HTML builder ──────────────────────────────────────────────────────────

def build_html(data: dict, base_dir: Path) -> str:
    meta     = data["meta"]
    sections = data["sections"]
    summary  = data["summary"]

    # Pre-load all tables from tables/ folder
    tables: dict[str, dict] = {}
    for sec in sections:
        for blk in sec.get("blocks", []):
            if blk.get("block_type") == "table_load":
                tbl = load_table(blk, base_dir)
                if tbl: tables[tbl["id"]] = tbl

    # Legend
    legend_html = ""
    for key, label in LEGEND:
        bg, fg = HIGHLIGHT_LEGEND_STYLES[key]
        legend_html += (
            f'<div class="legend-item">'
            f'<div class="legend-dot" style="background:{bg};outline:1px solid {fg}"></div>'
            f'<span>{e(label)}</span></div>'
        )

    # Section nav
    nav_links = "".join(f'<a href="#{e(s["id"])}">{e(s["title_zh"])}</a>' for s in sections)
    nav_links += '<a href="#summary">技術貢獻總覽</a>'

    # Body
    body_html = ""
    pair_idx  = 0

    for sec in sections:
        body_html += f"""
    <div id="{e(sec['id'])}" class="section-header">
      <h2>{e(sec['title_en'])}</h2>
      <div class="sec-zh">{e(sec['title_zh'])}</div>
    </div>"""

        blocks = sec.get("blocks", [])
        i = 0
        while i < len(blocks):
            blk   = blocks[i]
            btype = blk.get("block_type")

            # ── Paragraph ────────────────────────────────────────────────────
            if btype == "paragraph":
                # consume trailing table_refs
                trailing = []
                j = i + 1
                while j < len(blocks) and blocks[j].get("block_type") == "table_ref":
                    trailing.append(blocks[j]); j += 1

                ref_map = refs_in_blocks(trailing)
                tbl_refs_attr = ";".join(
                    f"{tid}:{','.join(str(r) for r in sorted(rows))}"
                    for tid, rows in ref_map.items()
                )
                data_attrs = f'data-pair-idx="{pair_idx}"'
                if tbl_refs_attr:
                    data_attrs += f' data-tbl-refs="{e(tbl_refs_attr)}"'

                ref_snips = "".join(
                    render_table_ref_snippet(r, tables.get(r.get("table_id","")))
                    for r in trailing
                )
                ann  = blk.get("annotation", {})
                rc   = ROLE_COLOURS.get(ann.get("role","結論"), "#6b7280")

                body_html += f"""
    <div class="pair" {data_attrs}>
      <div class="left-col">
        <div class="en-block">{render_en(blk["en"])}</div>
        <hr class="sep">
        <div class="zh-block">{render_en(blk["zh"])}</div>
        {ref_snips}
      </div>
      <div class="right-col">{render_annotation(ann, rc)}</div>
    </div>"""
                pair_idx += 1; i = j; continue

            # ── Figure ───────────────────────────────────────────────────────
            elif btype == "figure":
                left, right = render_figure(blk, base_dir)
                body_html += f"""
    <div class="pair" data-pair-idx="{pair_idx}">
      <div class="left-col">{left}</div>
      <div class="right-col">{right}</div>
    </div>"""
                pair_idx += 1

            # ── Table ─────────────────────────────────────────────────────────
            elif btype == "table_load":
                tid = blk.get("table_id", "")
                tbl = tables.get(tid)
                if not tbl: i += 1; continue

                # All table_refs in this section that cite this table
                sec_refs = refs_in_blocks(
                    [b for b in blocks if b.get("block_type")=="table_ref" and b.get("table_id")==tid]
                )
                tbl_html = render_table_html(tbl, sec_refs.get(tid, set()))
                ann_html = render_table_ann(tbl)

                # Collect following paragraphs/refs that belong to this table group
                inner_pairs = ""
                j = i + 1
                while j < len(blocks):
                    nb = blocks[j]; nb_type = nb.get("block_type")
                    if nb_type == "paragraph":
                        trailing2 = []
                        k = j+1
                        while k < len(blocks) and blocks[k].get("block_type") == "table_ref":
                            trailing2.append(blocks[k]); k += 1

                        ref_map2 = refs_in_blocks(trailing2)
                        tbl_refs2 = ";".join(
                            f"{t}:{','.join(str(r) for r in sorted(rs))}"
                            for t, rs in ref_map2.items()
                        )
                        da2 = f'data-pair-idx="{pair_idx}"'
                        if tbl_refs2: da2 += f' data-tbl-refs="{e(tbl_refs2)}"'

                        ann2 = nb.get("annotation", {})
                        rc2  = ROLE_COLOURS.get(ann2.get("role","結論"), "#6b7280")
                        ref_snips2 = "".join(
                            render_table_ref_snippet(r, tables.get(r.get("table_id","")))
                            for r in trailing2
                        )
                        inner_pairs += f"""
      <div class="pair" {da2}>
        <div class="left-col">
          <div class="en-block">{render_en(nb["en"])}</div>
          <hr class="sep">
          <div class="zh-block">{render_en(nb["zh"])}</div>
          {ref_snips2}
        </div>
        <div class="right-col">{render_annotation(ann2, rc2)}</div>
      </div>"""
                        pair_idx += 1; j = k
                    elif nb_type == "table_ref" and nb.get("table_id") == tid:
                        j += 1   # standalone ref already shown in snippets
                    else:
                        break

                body_html += f"""
    <div class="table-section" data-table-id="{e(tid)}">
      <div class="table-sticky-wrap">
        <div class="pair table-sticky-pair">
          <div class="left-col">{tbl_html}</div>
          <div class="right-col">{ann_html}</div>
        </div>
      </div>
      <div class="table-refs-body">{inner_pairs}</div>
    </div>"""
                i = j; continue

            # ── Standalone table_ref ──────────────────────────────────────────
            elif btype == "table_ref":
                snip = render_table_ref_snippet(blk, tables.get(blk.get("table_id","")))
                body_html += f"""
    <div class="pair" data-pair-idx="{pair_idx}">
      <div class="left-col">{snip}</div><div class="right-col"></div>
    </div>"""
                pair_idx += 1

            i += 1

    # Summary
    contribs = "".join(f"<li>{e(c)}</li>" for c in summary.get("contributions", []))
    apps     = "".join(f"<li>{e(a)}</li>" for a in summary.get("applications", []))

    evo_html = fish_html = ""
    if summary.get("evolutionary_path", {}).get("nodes"):
        evo_html = f'<div class="diagram-block"><h3>技術演化路徑 (Evolutionary Path)</h3>{build_evolutionary_path(summary["evolutionary_path"])}</div>'
    if summary.get("fishbone", {}).get("causes"):
        fish_html = f'<div class="diagram-block"><h3>研究問題根因 (Fishbone Diagram)</h3>{build_fishbone(summary["fishbone"])}</div>'

    authors    = ", ".join(e(a) for a in meta.get("authors", []))
    venue_year = e(f"{meta.get('venue','')} {meta.get('year','')}")

    return f"""<!DOCTYPE html>
<html lang="zh-TW">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{e(meta['title'])}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400&family=IBM+Plex+Sans:wght@400;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="style.css">
</head>
<body>

<nav id="navbar">
  <div class="paper-title">{e(meta['title'])}</div>
  <div class="legend">{legend_html}</div>
</nav>
<div id="sec-nav">{nav_links}</div>

<main>
  <div class="abstract-block">
    <div class="abstract-meta">{authors} &nbsp;·&nbsp; {venue_year}</div>
    <div class="abstract-body">{e(meta.get("abstract_zh",""))}</div>
  </div>

  {body_html}

  <section id="summary">
    <h2>技術貢獻總覽</h2>
    <div class="sum-grid">
      <div class="sum-block"><h3>研究問題與動機</h3><p>{e(summary.get("problem_gap",""))}</p></div>
      <div class="sum-block"><h3>核心技術貢獻</h3><ul>{contribs}</ul></div>
      <div class="one-line-box">{e(summary.get("one_line",""))}</div>
      <div class="sum-block"><h3>實驗結論摘要</h3><p>{e(summary.get("experiment_conclusion",""))}</p></div>
      <div class="sum-block"><h3>潛在應用與延伸</h3><ul>{apps}</ul></div>
      {evo_html}{fish_html}
    </div>
  </section>
</main>

<script>{SCROLL_JS}</script>
<script>{EVO_HOVER_JS}</script>
</body>
</html>"""

# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="AI Paper Annotator — JSON → HTML")
    parser.add_argument("json_file")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    json_path = Path(args.json_file).resolve()
    if not json_path.exists():
        print(f"Error: {json_path} not found.", file=sys.stderr); sys.exit(1)

    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    base_dir = json_path.parent
    out_path = Path(args.out).resolve() if args.out else json_path.with_suffix(".html")
    out_path.write_text(build_html(data, base_dir), encoding="utf-8")
    print(f"✅  Generated: {out_path}")
    print(f"   style.css must be in the same folder as the HTML.")
    print(f"   figures/  → {base_dir/'figures'}/")
    print(f"   tables/   → {base_dir/'tables'}/")

if __name__ == "__main__":
    main()
